export const guide: { category: string; title: string; command: string; detail: string }[] = [
  {category:'Apps & windows', title:'Open an app', command:'open notepad', detail:'Launch installed Windows apps by name.'},
  {category:'Apps & windows', title:'Switch to a window', command:'focus Chrome', detail:'Bring a matching app to the front.'},
  {category:'Apps & windows', title:'Arrange your workspace', command:'snap left current window', detail:'Also try maximize, minimize, restore, or snap right.'},
  {category:'Apps & windows', title:'Close a window', command:'close notepad', detail:'Windows keeps the app’s normal save prompt.'},
  {category:'Mouse & keyboard', title:'Type into an app', command:'type Hello, how are you?', detail:'Select your destination app first, then dictate.'},
  {category:'Mouse & keyboard', title:'Keyboard shortcut', command:'press control shift s', detail:'Use Ctrl, Alt, Shift, Windows, letters, or function keys.'},
  {category:'Mouse & keyboard', title:'Repeat a key', command:'press tab 3 times', detail:'Move between controls without touching your keyboard.'},
  {category:'Mouse & keyboard', title:'Precise voice clicks', command:'show grid', detail:'Say zoom five, then click three. Hide grid cancels.'},
  {category:'Mouse & keyboard', title:'Click a named control', command:'click the Save button', detail:'Click accessible buttons by name, or use the grid.'},
  {category:'Mouse & keyboard', title:'Move the pointer', command:'move mouse right 100', detail:'Move up, down, left, or right by pixels.'},
  {category:'Mouse & keyboard', title:'Scroll a page', command:'scroll down 3', detail:'Also supports up, left, and right.'},
  {category:'Mouse & keyboard', title:'Everyday editing', command:'copy', detail:'Also say paste, cut, undo, redo, select all, or save.'},
  {category:'Files & folders', title:'Find a document', command:'find PDF invoice', detail:'Search filenames locally. Choose a result by number.'},
  {category:'Files & folders', title:'Open a folder', command:'open downloads', detail:'Works with your Desktop, Documents, and Pictures folders.'},
  {category:'Files & folders', title:'Create a folder', command:'create folder Projects in documents', detail:'Create folders without overwriting existing items.'},
  {category:'Files & folders', title:'Copy a file', command:'copy file my budget to documents', detail:'Save a voice name for the source in Files & folders.'},
  {category:'Files & folders', title:'Recycle an item', command:'recycle file my old notes', detail:'Jarvis asks for confirmation before moving it to the Recycle Bin.'},
  {category:'System & media', title:'Set your volume', command:'set volume to 40 percent', detail:'Also say mute, unmute, volume up, or volume down.'},
  {category:'System & media', title:'Media playback', command:'next track', detail:'Previous track and play pause control your media player.'},
  {category:'System & media', title:'Capture your displays', command:'take a screenshot', detail:'Save a screenshot to your local Jarvis folder.'},
  {category:'System & media', title:'Power controls', command:'lock screen', detail:'Lock, sleep, restart, and shutdown require a yes or no.'},
  {category:'Notes & reminders', title:'Remember something', command:'take a note Buy milk on the way home', detail:'Notes are saved on this computer.'},
  {category:'Notes & reminders', title:'Set a reminder', command:'remind me in 10 minutes to drink water', detail:'Jarvis notifies you while the app is running.'},
  {category:'Notes & reminders', title:'Ask your local AI', command:'explain how a solar panel works', detail:'General conversation uses the AI model on this PC.'},
  {category:'Voice', title:'Switch language', command:'Urdu mode', detail:'English mode switches back. Spoken Urdu needs an Urdu Windows voice.'},
  {category:'Voice', title:'Interrupt a response', command:'stop speaking', detail:'Say Jarvis, stop speaking. Ctrl + Alt + Esc also pauses the microphone.'},
  {category:'Voice', title:'Pause the microphone', command:'pause listening', detail:'Use Activate or Ctrl + Alt + J to listen again.'},
];
