import { Activity, ArrowRight, AudioLines, CheckCircle2, Clock3, Cpu, FileText, FolderOpen, Mic, MicOff, ShieldCheck, Square, Terminal, Zap } from "lucide-react";
import type { Snapshot, TaskStatus } from "./types";

export interface ResponseTiming { first_text_ms: number | null; duration_ms: number; action: string; success: boolean }
interface Props {
  snapshot: Snapshot; connected: boolean; cpu: number; tasks: TaskStatus[];
  timing: ResponseTiming | null; talk: () => void; reminders: () => void;
  activate: () => void; stop: () => void; command: (text: string) => void;
}
const label = (value: string) => value.replaceAll("_", " ");
const stateLabels: Record<string, string> = { succeeded: "Completed", running: "Running", failed: "Failed", cancelled: "Stopped", waiting_confirmation: "Needs your input", queued: "Queued" };
const toolLabels: Record<string, string> = { chat: "Local conversation", open: "Open application or file", file_action: "File operation", web_search: "Browser search", note: "Save note", reminder: "Create reminder", keys: "Keyboard control", mouse: "Mouse control" };
export default function MissionControl({ snapshot, connected, cpu, tasks, timing, talk, reminders, activate, stop, command }: Props) {
  const now = new Date();
  const end = new Date(now); end.setHours(23, 59, 59, 999);
  const due = snapshot.reminders.filter(r => r.due * 1000 <= end.getTime()).sort((a,b) => a.due-b.due);
  const hour = now.getHours();
  const greeting = hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening";
  const name = snapshot.settings.user_name === "You" ? "" : ", " + snapshot.settings.user_name;
  const active = snapshot.current_task;
  return <div className="mission-control">
    <div className="page-heading"><div><span className="eyebrow">YOUR PERSONAL COMMAND CENTER</span><h1>{greeting}{name}.</h1><p>Your desktop, voice, and plans. One place to stay in control.</p></div><span className="mission-date">{now.toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"})}</span></div>
    <div className="mission-summary" aria-label="Live system status">
      <article><span className="mission-icon"><Mic size={18}/></span><div><small>VOICE CHANNEL</small><strong>{!connected ? "Disconnected" : snapshot.listening ? "Listening" : "Paused"}</strong><span>{snapshot.listening ? "Say “"+snapshot.settings.wake_word+"” to begin" : "Activate when you are ready"}</span></div></article>
      <article><span className="mission-icon"><Cpu size={18}/></span><div><small>INTELLIGENCE</small><strong>{snapshot.provider.online ? "Online provider" : "Local processing"}</strong><span>{snapshot.chat_ready ? "Chat model available" : "Chat model needs setup"}</span></div></article>
      <article><span className="mission-icon"><Clock3 size={18}/></span><div><small>DUE BY TONIGHT</small><strong>{connected ? due.length : "—"} reminders</strong><span>{due.length ? "Includes anything overdue" : "Your schedule is clear"}</span></div></article>
      <article><span className="mission-icon"><Zap size={18}/></span><div><small>LAST RESPONSE</small><strong>{timing ? (timing.duration_ms/1000).toFixed(1)+" s" : "—"}</strong><span>{timing?.first_text_ms != null ? "First text in "+(timing.first_text_ms/1000).toFixed(1)+" s" : "Measured after a command"}</span></div></article>
    </div>
    <div className="mission-grid"><section className="panel mission-core"><div className="section-heading"><h3><AudioLines size={18}/> Assistant core</h3><span>{connected ? "CONNECTED" : "ENGINE DISCONNECTED"}</span></div>
      <div className="core-presentation"><div className={"core-emblem "+(snapshot.busy ? "processing" : "")} aria-hidden="true"><span/><span/><AudioLines size={42}/></div><div><span className="eyebrow">{snapshot.speaking ? "SPEAKING" : snapshot.busy ? "WORKING" : "AWAITING YOUR COMMAND"}</span><h2>{snapshot.busy ? "On it." : "Ready when you are."}</h2><p>{snapshot.status}</p><div className="mission-actions"><button className="button primary" disabled={!connected} onClick={talk}><Terminal size={16}/> Open conversation <ArrowRight size={14}/></button><button className="button" disabled={!connected} onClick={activate}>{snapshot.listening ? <MicOff size={16}/> : <Mic size={16}/>} {snapshot.listening ? "Pause microphone" : "Activate voice"}</button></div></div></div>
      <div className="mission-pipeline"><div><i className={snapshot.listening ? "lit" : ""}/><span>Input</span><b>{snapshot.listening ? "Microphone on" : "Text available"}</b></div><ArrowRight size={13}/><div><i className={snapshot.busy ? "lit" : ""}/><span>Action</span><b>{snapshot.busy ? "In progress" : "Standing by"}</b></div><ArrowRight size={13}/><div><i className={snapshot.speaking ? "lit" : ""}/><span>Response</span><b>{snapshot.speaking ? "Speaking" : "Voice + text"}</b></div></div>
      <div className="mission-stop"><span><ShieldCheck size={14}/> You stay in control of every session.</span><button disabled={!connected} onClick={stop}><Square size={12}/> Emergency stop <kbd>Ctrl Alt Esc</kbd></button></div>
    </section><section className="panel mission-agenda"><div className="section-heading"><h3><Clock3 size={17}/> Today’s focus</h3><button className="text-link" onClick={reminders}>Manage <ArrowRight size={13}/></button></div><div className="agenda-body">{due.length ? due.slice(0,4).map(r=><article key={r.id}><span className={r.due*1000<now.getTime() ? "overdue" : ""}>{r.due*1000<now.getTime() ? "Due" : new Date(r.due*1000).toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})}</span><p>{r.text}</p></article>) : <div className="agenda-empty"><CheckCircle2 size={28}/><h3>A little room to focus.</h3><p>No pending reminders due today. Add your next task when you need it.</p><button className="button compact" onClick={reminders}>Plan a reminder <ArrowRight size={14}/></button></div>}</div><small>Keep Jarvis running for local reminders.</small></section></div>
    <div className="mission-grid mission-lower"><section className="panel"><div className="section-heading"><h3><Activity size={17}/> Session activity</h3><span>{tasks.length} RECENT TASKS</span></div><div className="mission-tasks">{tasks.length ? [...tasks].reverse().slice(0,6).map(task=><article key={task.id}><span className={"task-dot state-"+task.state}/><div><strong>{toolLabels[task.steps.at(-1)?.tool ?? ""] || label(task.steps.at(-1)?.tool || "Command")}</strong><small>{label(task.source)} · {task.steps.length} {task.steps.length===1?"step":"steps"}</small></div><span className={"task-outcome state-"+task.state}>{stateLabels[task.state] || label(task.state)}</span></article>) : <div className="inline-empty">Your next command will appear here. This view shows the current session; security audit records remain local.</div>}</div>{active?.steps.at(-1)?.verification === "request_accepted" && <div className="verification-note">Last tool accepted its request. The final desktop state was not independently verified.</div>}</section>
    <section className="panel mission-health"><div className="section-heading"><h3><Cpu size={17}/> On this computer</h3><span>LIVE</span></div><div className="health-body"><div className="health-meter"><span>CPU <b>{connected ? Math.round(cpu)+"%" : "—"}</b></span><meter min={0} max={100} value={cpu} aria-label="CPU usage"/></div><div className="health-meter"><span>Memory <b>{connected ? Math.round(snapshot.memory_percent)+"%" : "—"}</b></span><meter min={0} max={100} value={snapshot.memory_percent} aria-label="Memory usage"/></div><div className="health-detail"><span>Search index</span><b>{snapshot.index_count.toLocaleString()} items</b></div><div className="health-detail"><span>Owner authentication</span><b className={snapshot.security.owner_authenticated?"":"needs-setup"}>{snapshot.security.owner_authenticated ? "Authorized" : "Not configured"}</b></div><div className="mission-shortcuts"><button disabled={!connected||snapshot.busy} onClick={()=>command("open notepad")}><FileText size={15}/> Notepad</button><button disabled={!connected||snapshot.busy} onClick={()=>command("open downloads")}><FolderOpen size={15}/> Downloads</button></div></div></section></div>
  </div>;
}
