import { useEffect, useState } from 'react';
import { open } from '@tauri-apps/plugin-dialog';
import { AudioLines, Check, ChevronRight, Cpu, Download, FolderOpen, Mic, Plus, RefreshCw, Save, ShieldCheck, SlidersHorizontal, Volume2, X } from 'lucide-react';
import { request } from './bridge';
import PersonalVoiceSettings from './PersonalVoiceSettings';
import type { Settings, Snapshot } from './types';
interface Props { snapshot: Snapshot; connected: boolean; save: (values: Partial<Settings>)=>Promise<void>; setup: {message:string;running:boolean}; download:()=>void; onError:(message:string)=>void }
export default function SettingsPage({ snapshot, connected, save, setup, download, onError }: Props) {
  const [values,setValues]=useState(snapshot.settings);
  const [devices,setDevices]=useState<{microphones:{id:number;name:string}[];voices:{id:string;name:string}[]}>({microphones:[],voices:[]});
  const [saving,setSaving]=useState(false);
  const [saved,setSaved]=useState(false);
  const [pin,setPin]=useState('');
  const [owner,setOwner]=useState(snapshot.owner);
  const [enrolling,setEnrolling]=useState('');
  useEffect(()=>setValues(snapshot.settings),[snapshot.settings]);
  useEffect(()=>setOwner(snapshot.owner),[snapshot.owner]);
  const change=<K extends keyof Settings>(key:K,value:Settings[K])=>{setValues(v=>({...v,[key]:value}));setSaved(false);};
  const refresh=()=>{void request<typeof devices>('devices').then(setDevices).catch(e=>onError(String(e)));};
  useEffect(()=>{if(connected)refresh();},[connected]);
  const persist=async()=>{setSaving(true);try{await save(values);setSaved(true);}catch(e){onError(String(e));}finally{setSaving(false);}};
  const chooseFolder=async()=>{try{const path=await open({directory:true,multiple:false,title:'Choose a searchable folder'});if(typeof path==='string')change('search_roots',[...new Set([...values.search_roots,path])]);}catch(e){onError(String(e));}};
  const chooseModel=async(speech:boolean)=>{try{const path=await open({directory:speech,multiple:false,title:speech?'Choose a local speech model folder':'Choose a local chat model',...(!speech?{filters:[{name:'Local model',extensions:['gguf']}]}:{})});if(typeof path==='string')change(speech?'whisper_path':'llm_path',path);}catch(e){onError(String(e));}};
  const ownerAction=async(op: 'owner_set_pin'|'owner_delete_pin'|'owner_face_camera'|'owner_delete_face'|'owner_voice_enroll'|'owner_delete_voice', payload:Record<string,unknown>={})=>{setEnrolling(op);try{const result=await request<typeof owner>(op,payload);setOwner(result);}catch(e){onError(String(e));}finally{setEnrolling('');}};
  const toggle=(key:'listen_on_startup'|'require_wake_word'|'speech_enabled'|'close_to_tray'|'start_with_windows',title:string,detail:string)=><label className="toggle-row"><div><strong>{title}</strong><small>{detail}</small></div><input type="checkbox" checked={values[key]} onChange={e=>change(key,e.target.checked)}/><span className="switch"/></label>;
  return <><div className="page-heading"><div><span className="eyebrow">FEELS LIKE YOU.</span><h1>Make Jarvis your own.</h1><p>A voice you like. A workspace you know. Everything stays local.</p></div><span className="pill green"><ShieldCheck size={13}/> Private by design</span></div>
    <div className="settings-layout"><div className="settings-main">
      <PersonalVoiceSettings connected={connected} values={values} change={change} save={save} onError={onError}/>
      <section className="panel settings-section"><div className="section-heading"><h3><Mic size={18}/> Listening</h3><button className="text-link" disabled={!connected} onClick={refresh}><RefreshCw size={13}/> Refresh devices</button></div><div className="settings-fields"><div className="field-grid"><label>Recognition language<select value={values.language} onChange={e=>change('language',e.target.value)}><option value="auto">English + Urdu · automatic</option><option value="en">English</option><option value="ur">Urdu</option></select></label><label>Wake word<input value={values.wake_word} onChange={e=>change('wake_word',e.target.value)} placeholder="jarvis" maxLength={30}/></label></div><label>Microphone<select value={values.microphone_device??''} onChange={e=>change('microphone_device',e.target.value===''?null:Number(e.target.value))}><option value="">Windows default microphone</option>{devices.microphones.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{toggle('listen_on_startup','Listen when Jarvis opens','Start hands-free listening as soon as the desktop app launches.')}{toggle('require_wake_word','Listen for my wake word','Begin commands with “'+(values.wake_word||'Jarvis')+'” during hands-free listening.')}<label>Pause before recognizing <b>{values.silence_ms} ms</b><input type="range" min={300} max={3000} step={50} value={values.silence_ms} onChange={e=>change('silence_ms',Number(e.target.value))}/><small>600 ms responds sooner. 850–1200 ms allows longer pauses between words. Changes apply to the next listening session.</small></label><label>Fallback noise filtering<select value={values.vad_aggressiveness} onChange={e=>change('vad_aggressiveness',Number(e.target.value))}>{['Light','Balanced','Strong','Very strong'].map((s,i)=><option key={i} value={i}>{s}</option>)}</select></label></div></section>
      <section className="panel settings-section"><div className="section-heading"><h3><Volume2 size={18}/> Speaking</h3><span>OFFLINE VOICE</span></div><div className="settings-fields"><label>Assistant voice<select value={values.voice_id} onChange={e=>change('voice_id',e.target.value)}><option value="">Windows default voice</option>{devices.voices.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div className="field-grid"><label>Speaking speed <b>{values.voice_rate>0?'+':''}{values.voice_rate}</b><input type="range" min={-10} max={10} value={values.voice_rate} onChange={e=>change('voice_rate',Number(e.target.value))}/></label><label>Voice volume <b>{values.voice_volume}%</b><input type="range" min={0} max={100} value={values.voice_volume} onChange={e=>change('voice_volume',Number(e.target.value))}/></label></div>{toggle('speech_enabled','Read responses aloud','Jarvis can speak as well as show its answers.')}<div className="voice-test"><span>Spoken Urdu requires an installed Urdu Windows voice.</span><button className="button compact" disabled={!connected||saving} onClick={()=>{void(async()=>{try{await save(values);await request('voice_test');}catch(e){onError(String(e));}})();}}><AudioLines size={15}/> Save & test voice</button></div></div></section>
      <section className="panel settings-section"><div className="section-heading"><h3><ShieldCheck size={18}/> Security &amp; Owner</h3><span>{owner.overall?'CONFIGURED':'SETUP REQUIRED'}</span></div><div className="settings-fields"><p>Configure the owner identity and security. Biometric data stays local and does not replace PIN confirmation for high-risk actions.</p><div className="field-grid"><label>Owner name<input value={values.user_name} onChange={e=>change('user_name',e.target.value)} maxLength={60}/></label><label>Assistant name<input value={values.assistant_name} onChange={e=>change('assistant_name',e.target.value)} maxLength={60}/></label></div><label>Owner email for recovery (optional)<input type="email" value={values.owner_email} onChange={e=>change('owner_email',e.target.value)} maxLength={160}/></label><div className="field-grid"><label>Owner PIN/password<input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder={owner.pin_configured?'Configured':'Not configured'}/><button className="button compact" disabled={!connected||pin.length<4||!!enrolling} onClick={()=>{void ownerAction('owner_set_pin',{pin}).then(()=>setPin(''));}}>Set PIN</button></label><div className="model-row"><span>PIN status</span><b className={owner.pin_configured?'ready':''}>{owner.pin_configured?'✓ Configured':'Not configured'}</b></div></div><div className="field-grid"><div className="biometric-card"><strong>FACE ID</strong><small>{owner.camera_available?'Camera available':'Camera/OpenCV unavailable'}</small><b>{owner.face_enrolled?'✓ Face enrolled':'Not enrolled'}</b><button className="button compact" disabled={!connected||!!enrolling||!owner.camera_available} onClick={()=>void ownerAction('owner_face_camera',{samples:8})}>{enrolling==='owner_face_camera'?'Enrolling…':owner.face_enrolled?'Re-enroll':'Start face enrollment'}</button><button className="text-link" disabled={!connected||!!enrolling} onClick={()=>void ownerAction('owner_delete_face')}>Delete local face data</button></div><div className="biometric-card"><strong>VOICE ID</strong><small>{owner.microphone_message}</small><b>{owner.voice_enrolled?`✓ Voice enrolled (${owner.voice_samples} samples)`:'Not enrolled'}</b><button className="button compact" disabled={!connected||!!enrolling||!owner.microphone_available} onClick={()=>void ownerAction('owner_voice_enroll',{samples:3,seconds:4})}>{enrolling==='owner_voice_enroll'?'Recording…':owner.voice_enrolled?'Re-record voice':'Start voice enrollment'}</button><button className="text-link" disabled={!connected||!!enrolling} onClick={()=>void ownerAction('owner_delete_voice')}>Delete local voice data</button></div></div><div className="model-row"><span>Overall owner status</span><b className={owner.overall?'ready':''}>{owner.overall_message}</b></div></div></section>
      <section className="panel settings-section"><div className="section-heading"><h3><SlidersHorizontal size={18}/> Your workspace</h3></div><div className="settings-fields"><label>Your name<input value={values.user_name} onChange={e=>change('user_name',e.target.value)} maxLength={60}/></label>{toggle('close_to_tray','Keep working in the background','Closing the window keeps Jarvis available in the system tray.')}{toggle('start_with_windows','Start with Windows','Launch Jarvis in the system tray when you sign in.')}<label>Audit retention (days)<input type="number" min={1} max={3650} value={values.audit_retention_days} onChange={e=>change('audit_retention_days',Number(e.target.value))}/><small>Security audit records contain action metadata, not conversation text. Retention cleanup runs when the engine starts.</small></label><div className="folder-heading"><label>Searchable folders</label><button className="text-link" disabled={!connected} onClick={()=>void chooseFolder()}><Plus size={14}/> Add folder</button></div><div className="folder-roots">{values.search_roots.map(path=><div key={path}><FolderOpen size={16}/><span title={path}>{path}</span><button className="icon-button" aria-label={`Remove ${path} from search`} onClick={()=>change('search_roots',values.search_roots.filter(p=>p!==path))}><X size={14}/></button></div>)}</div></div></section>
    </div><aside className="settings-aside"><section className="panel model-card"><div className="model-icon"><Cpu size={26}/></div><span className="eyebrow">LOCAL INTELLIGENCE</span><h2>Ready, even offline.</h2><p>Speech and chat run directly on your computer. No account or API key needed.</p><div className="model-row"><span><Mic size={16}/> Voice recognition</span><b className={snapshot.speech_ready?'ready':''}>{snapshot.speech_ready?<><Check size={12}/> Ready</>:'Needs setup'}</b></div><div className="model-row"><span><Cpu size={16}/> Local chat</span><b className={snapshot.chat_ready?'ready':''}>{snapshot.chat_ready?<><Check size={12}/> Ready</>:'Needs setup'}</b></div><button className="button primary" disabled={!connected||setup.running} onClick={download}><Download size={16}/>{setup.running?'Preparing models…':snapshot.chat_ready&&snapshot.speech_ready?'Check / repair models':'Prepare local models'}</button><small>A one-time download of about 1.3 GB is needed if models are missing. After setup, voice and chat work offline.</small>{setup.message&&<div className="setup-progress" role="status">{setup.running&&<RefreshCw className="spin" size={13}/>} {setup.message}</div>}<div className="model-pickers"><button disabled={!connected} onClick={()=>void chooseModel(true)}>Choose speech folder <ChevronRight size={14}/></button><button disabled={!connected} onClick={()=>void chooseModel(false)}>Choose chat model <ChevronRight size={14}/></button></div></section><section className="settings-help"><ShieldCheck size={22}/><h3>Yours stays yours.</h3><p>Settings, conversation history, notes, and reminders are saved locally.</p><code>{snapshot.data_directory||'Your local Jarvis folder'}</code></section><div className="shortcut-card"><span className="shortcut-symbol">⌘</span><h3>Always within reach.</h3><p><kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>J</kbd><span>Listen to one command</span></p><p><kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Esc</kbd><span>Stop and pause the microphone</span></p></div></aside></div>
    <div className="settings-save"><span>{saved?<><Check size={15}/> Your preferences are saved.</>:'Changes apply when you save your preferences.'}</span><button className="button primary" disabled={!connected||saving||!values.wake_word.trim()||!values.user_name.trim()} onClick={()=>void persist()}><Save size={16}/>{saving?'Saving…':'Save preferences'}</button></div></>;
}
